INSERT INTO OPERATION_TYPE (OPERATION_TYPE_ID, DESCRIPTION)
VALUES (1, 'PURCHASE')
ON CONFLICT (OPERATION_TYPE_ID) DO NOTHING;

INSERT INTO OPERATION_TYPE (OPERATION_TYPE_ID, DESCRIPTION)
VALUES (2, 'INSTALLMENT PURCHASE')
ON CONFLICT (OPERATION_TYPE_ID) DO NOTHING;

INSERT INTO OPERATION_TYPE (OPERATION_TYPE_ID, DESCRIPTION)
VALUES (3, 'WITHDRAWAL')
ON CONFLICT (OPERATION_TYPE_ID) DO NOTHING;

INSERT INTO OPERATION_TYPE (OPERATION_TYPE_ID, DESCRIPTION)
VALUES (4, 'PAYMENT')
ON CONFLICT (OPERATION_TYPE_ID) DO NOTHING;